//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.Mesplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class etsng
    {
        public string etsng1 { get; set; }
        public string name { get; set; }
    }
}
