//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Collections.Generic;
    
    public partial class krt_Naftan_orc_sapod
    {
        public long keykrt { get; set; }
        public long keysbor { get; set; }
        public string nomot { get; set; }
        public System.DateTime dt { get; set; }
        public string gruname { get; set; }
        public short vidsbr { get; set; }
        public string namesbr { get; set; }
        public decimal sm_no_nds { get; set; }
        public decimal sm_nds { get; set; }
        public decimal sm { get; set; }
        public decimal stnds { get; set; }
        public string UNI_OTPR { get; set; }
        public int nper { get; set; }
        public string nkrt { get; set; }
        public string p_type { get; set; }
        public System.DateTime DtBuhOtchet { get; set; }
        public System.DateTime date_obrabot { get; set; }
        public byte tdoc { get; set; }
        public int ORC_ID_ED { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<int> id_otpr { get; set; }
        public Nullable<short> type_doc { get; set; }
        public Nullable<short> cod_sbor { get; set; }
        public Nullable<System.DateTime> date_raskr { get; set; }
        public string num_doc { get; set; }
        public Nullable<decimal> cena { get; set; }
        public Nullable<decimal> kol { get; set; }
        public Nullable<decimal> summa { get; set; }
        public Nullable<decimal> nds { get; set; }
        public string textm { get; set; }
        public Nullable<int> ID_ED { get; set; }
    
        public virtual krt_Naftan krt_Naftan { get; set; }
    }
}
