//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_kart
    {
        public int id { get; set; }
        public string uni_kart { get; set; }
        public string num_kart { get; set; }
        public string cod_stan { get; set; }
        public Nullable<System.DateTime> date_okrt { get; set; }
        public string cod_pl { get; set; }
        public Nullable<short> nod_pl { get; set; }
        public string mfo { get; set; }
        public string rash { get; set; }
        public Nullable<int> num_plat_por { get; set; }
        public Nullable<System.DateTime> date_plat_por { get; set; }
        public Nullable<short> type_kart { get; set; }
        public string cod_ls { get; set; }
        public string num_dogovor { get; set; }
        public string cod_currency { get; set; }
        public Nullable<decimal> summa { get; set; }
        public Nullable<long> state { get; set; }
        public string num_fdu93 { get; set; }
        public Nullable<System.DateTime> date_fdu93 { get; set; }
        public Nullable<int> pr_external_work { get; set; }
        public Nullable<long> state_dbf { get; set; }
        public Nullable<System.DateTime> date_zkrt { get; set; }
    }
}
