//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OBDEntities : DbContext
    {
        public OBDEntities()
            : base("name=OBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<v_akt> v_akts { get; set; }
        public DbSet<v_akt_sb> v_akt_sbs { get; set; }
        public DbSet<v_akt_vag> v_akt_vags { get; set; }
        public DbSet<v_kart> v_karts { get; set; }
        public DbSet<v_nach> v_nachs { get; set; }
        public DbSet<v_o_v> v_o_vs { get; set; }
        public DbSet<v_otpr> v_otprs { get; set; }
        public DbSet<v_pam> v_pams { get; set; }
        public DbSet<v_pam_sb> v_pam_sbs { get; set; }
        public DbSet<v_pam_vag> v_pam_vags { get; set; }
    }
}
