//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_akt_sb
    {
        public int id { get; set; }
        public int id_akt { get; set; }
        public int id_vag { get; set; }
        public string kod_sb { get; set; }
        public Nullable<decimal> sum_sb { get; set; }
        public Nullable<decimal> nds_sb { get; set; }
        public string textm { get; set; }
    }
}
