//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_akt
    {
        public int id { get; set; }
        public string kodls { get; set; }
        public string nakt { get; set; }
        public Nullable<System.DateTime> dakt { get; set; }
        public string kodkl { get; set; }
        public string nkrt { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> pr_external_work { get; set; }
    }
}
