//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_nach
    {
        public int id { get; set; }
        public int id_kart { get; set; }
        public Nullable<int> id_otpr { get; set; }
        public string uni_otpr { get; set; }
        public string cod_kl { get; set; }
        public Nullable<short> nod_kl { get; set; }
        public Nullable<int> type_doc { get; set; }
        public Nullable<short> oper { get; set; }
        public string cod_sbor { get; set; }
        public Nullable<System.DateTime> date_raskr { get; set; }
        public string num_doc { get; set; }
        public Nullable<decimal> cena { get; set; }
        public Nullable<decimal> kol { get; set; }
        public Nullable<decimal> summa { get; set; }
        public Nullable<decimal> nds { get; set; }
        public string cod_currency { get; set; }
        public string num_kart_sd { get; set; }
        public string textm { get; set; }
        public Nullable<int> id_ed { get; set; }
    }
}
