//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pam
    {
        public int id_ved { get; set; }
        public string nved { get; set; }
        public Nullable<System.DateTime> dved { get; set; }
        public Nullable<System.DateTime> dzakr { get; set; }
        public string kodkl { get; set; }
        public string nkrt { get; set; }
        public Nullable<int> id_kart { get; set; }
        public string nper { get; set; }
        public Nullable<int> state { get; set; }
    }
}
