//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pam_sb
    {
        public int id_ved { get; set; }
        public string kod_sb { get; set; }
        public Nullable<decimal> sum_sb { get; set; }
        public Nullable<decimal> nds_sb { get; set; }
        public Nullable<short> kodusl { get; set; }
        public string textm { get; set; }
        public Nullable<System.DateTime> d_sb { get; set; }
        public Nullable<int> kol_oper { get; set; }
    }
}
