//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pam
    {
        public int id_ved { get; set; }
        public string id_ved_dbf { get; set; }
        public string kodls { get; set; }
        public string nved { get; set; }
        public Nullable<System.DateTime> dved { get; set; }
        public Nullable<System.DateTime> dzakr { get; set; }
        public string kodkl { get; set; }
        public string ndog { get; set; }
        public Nullable<decimal> r_oba { get; set; }
        public Nullable<short> pr_put { get; set; }
        public string put { get; set; }
        public Nullable<short> pr_lok { get; set; }
        public Nullable<short> pr_lokf { get; set; }
        public Nullable<short> prlokub { get; set; }
        public Nullable<short> pr_razg { get; set; }
        public string nkrt { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<short> n_tab { get; set; }
        public Nullable<short> v_ob { get; set; }
        public string nper { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> pr_external_work { get; set; }
    }
}
