//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_02_podhod
    {
        public string n_vag { get; set; }
        public Nullable<int> massa_t { get; set; }
        public string st_nazn { get; set; }
        public string kod_etsng { get; set; }
        public string kod_pol { get; set; }
        public string prim { get; set; }
        public Nullable<System.DateTime> date_oper_v { get; set; }
        public Nullable<short> oper { get; set; }
        public string n_otpr { get; set; }
    }
}
