//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_akt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public v_akt()
        {
            this.v_akt_vag = new HashSet<v_akt_vag>();
        }
    
        public int id { get; set; }
        public string nakt { get; set; }
        public Nullable<System.DateTime> dakt { get; set; }
        public string kodkl { get; set; }
        public string nkrt { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<int> state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_akt_vag> v_akt_vag { get; set; }
    }
}
