//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_kart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public v_kart()
        {
            this.v_nach = new HashSet<v_nach>();
        }
    
        public int id { get; set; }
        public string num_kart { get; set; }
        public Nullable<System.DateTime> date_okrt { get; set; }
        public string cod_pl { get; set; }
        public Nullable<short> type_kart { get; set; }
        public string cod_ls { get; set; }
        public Nullable<decimal> summa { get; set; }
        public Nullable<long> state { get; set; }
        public Nullable<System.DateTime> date_fdu93 { get; set; }
        public Nullable<System.DateTime> date_zkrt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_nach> v_nach { get; set; }
    }
}
