//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_otpr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public v_otpr()
        {
            this.v_o_v = new HashSet<v_o_v>();
        }
    
        public int id { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<short> oper { get; set; }
        public Nullable<System.DateTime> date_oper { get; set; }
        public string n_otpr { get; set; }
        public string cod_kl_otpr { get; set; }
        public string cod_klient_pol { get; set; }
        public string g6 { get; set; }
        public string g4 { get; set; }
        public string g11 { get; set; }
        public string cod_tvk_etsng { get; set; }
        public Nullable<int> massa_otpr { get; set; }
        public Nullable<int> type_doc { get; set; }
        public string adr_otpr { get; set; }
        public string adr_pol { get; set; }
        public string nam_otpr { get; set; }
        public string nam_pol { get; set; }
        public string fio_tk { get; set; }
        public string g8 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_o_v> v_o_v { get; set; }
    }
}
