//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pam_vag
    {
        public int id_vag { get; set; }
        public int id_ved { get; set; }
        public string nomvag { get; set; }
        public string kodgr { get; set; }
        public Nullable<short> kodop { get; set; }
        public Nullable<System.DateTime> d_pod { get; set; }
        public Nullable<System.DateTime> d_ub { get; set; }
    
        public virtual v_pam v_pam { get; set; }
    }
}
