//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContexts.OBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public v_pam()
        {
            this.v_pam_vag = new HashSet<v_pam_vag>();
        }
    
        public int id_ved { get; set; }
        public string nved { get; set; }
        public Nullable<System.DateTime> dved { get; set; }
        public Nullable<System.DateTime> dzakr { get; set; }
        public string kodkl { get; set; }
        public string nkrt { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<int> state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_pam_vag> v_pam_vag { get; set; }
    }
}
