//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Collections.Generic;
    
    public partial class krt_DetailsProgress
    {
        public byte tDoc { get; set; }
        public short vidSbr { get; set; }
        public byte state { get; set; }
        public Nullable<System.DateTime> StDetailDate { get; set; }
        public string nameSbr { get; set; }
        public Nullable<System.DateTime> lastDate { get; set; }
    }
}
