//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Collections.Generic;
    
    public partial class krt_Guild18
    {
        public int id { get; set; }
        public System.DateTime reportPeriod { get; set; }
        public Nullable<int> warehouse { get; set; }
        public Nullable<int> idDeliviryNote { get; set; }
        public Nullable<byte> type_doc { get; set; }
        public Nullable<int> idSrcDocument { get; set; }
        public bool codeType { get; set; }
        public int code { get; set; }
        public decimal sum { get; set; }
        public decimal rateVAT { get; set; }
        public Nullable<long> idScroll { get; set; }
        public Nullable<int> idCard { get; set; }
    }
}
