//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Collections.Generic;
    
    public partial class krt_DetailsProgress
    {
        public byte tDoc { get; set; }
        public short vidSbr { get; set; }
        public byte state { get; set; }
        public Nullable<System.DateTime> StDetailDate { get; set; }
        public string nameSbr { get; set; }
        public Nullable<System.DateTime> lastDate { get; set; }
    }
}
