//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Collections.Generic;
    
    public partial class orc_krt
    {
        public orc_krt()
        {
            this.orc_sbor = new HashSet<orc_sbor>();
        }
    
        public long KEYKRT { get; set; }
        public Nullable<int> NKRT { get; set; }
        public Nullable<int> NTREB { get; set; }
        public Nullable<System.DateTime> DTTREB { get; set; }
        public Nullable<System.DateTime> DTOPEN { get; set; }
        public Nullable<System.DateTime> DTCLOSE { get; set; }
        public Nullable<decimal> SMTREB { get; set; }
        public Nullable<decimal> NDSTREB { get; set; }
        public Nullable<int> U_KOD { get; set; }
        public string P_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_OBRABOT { get; set; }
        public bool IN_REAL { get; set; }
    
        public virtual ICollection<orc_sbor> orc_sbor { get; set; }
    }
}
