//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORCEntities : DbContext
    {
        public ORCEntities()
            : base("name=ORCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<krt_Naftan> krt_Naftans { get; set; }
        public DbSet<krt_Naftan_orc_sapod> krt_Naftan_orc_sapods { get; set; }
        public DbSet<orc_krt> orc_krts { get; set; }
        public DbSet<orc_sbor> orc_sbors { get; set; }
    }
}
