//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaftanRailway.Domain.Concrete.DbContext.ORC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORCEntities : DbContext
    {
        public ORCEntities()
            : base("name=ORCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<krt_Guild18> krt_Guild18s { get; set; }
        public virtual DbSet<krt_Naftan> krt_Naftans { get; set; }
        public virtual DbSet<krt_Naftan_orc_sapod> krt_Naftan_orc_sapods { get; set; }
        public virtual DbSet<orc_krt> orc_krts { get; set; }
        public virtual DbSet<orc_sbor> orc_sbors { get; set; }
    }
}
